### ISSUE TITLE
Allow disabling chunked object support

### ISSUE THREAD

**Issue by DemiMarie** [UBMLtonGroup/RTMLton#2]
Some applications would like the multicore features and the green threads, but don't need a real-time GC.  It would be nice if the chunked object support (which introduces overhead) could be made optional.

**Comment by bhargavshivkumar** [comment]
@DemiMarie did you take a look at [MultiMLton](https://github.com/kayceesrk/multiMLton)?  We will make note of your input and see if a flagged chunked object model is feasible.  Thanks!

**Comment by DemiMarie** [comment]
@bhargavshivkumar I did, but it is out of date and (as far as I know) only works with the C backend, not with the LLVM or native backends.  It is also not portable.

On the other hand, this branch seems to be under very active development, hence the feature request.
