### ISSUE TITLE
Compilation failure on 32-bit Fedora 30

### ISSUE THREAD

**Issue by jcoo092** [UBMLtonGroup/RTMLton#22]
Hi RTMLton team,

I have just attempted to compile RTMLton on a fresh 32-bit Fedora 30 virtual machine (30 being seemingly the last release that had a 32-bit version).  I downloaded the 'Fedora-Workstation-Live-i386-30-1.2.iso' file from a mirror (it has SHA-256 hash 78256B0646C8B07A1990BC2729BF3D907B405A8192BAAB9F4DD9C3760134067C), ran the built-in updater and restarted, then installed MLton (and its prerequisites) in accordance with the MLton repo's instructions (I'm not sure whether RTMLton requires, or even gets along with, regular MLton).  I then cloned the RTMLton repo from the current head at https://github.com/UBMLtonGroup/RTMLton.git (which appears to be commit c7924ad5b10a07ad14c9085d90af8a5e21529295) and ran `./compile.sh`.

Eventually, it terminated with this message:

> cc1: all warnings being treated as errors
> make[1]: *** [Makefile:358: gc.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/home/jcooper/Downloads/RTMLton/runtime'
> make: *** [Makefile:200: runtime] Error 2
> Try:
>  ./build/bin/mlton  -codegen c -keep g -debug true -expert true -verbose 3 -keep ssa -keep ssa2 -keep rssa -keep machine -cc-opt -O0 ub/justprint.sml
>  ./justprint
> 
>  adjust STACKLET_DEBUG in include/c-chunk.h and
>  cp include/c-chunk.h build/lib/include/
>  to debug stacklets

Scrolling up through the output, the only errors I could spot amongst the output were the below, which all appear to be connected to the one compiler invocation:

> gcc -std=c11  -D_GNU_SOURCE -D_USE_GNU  -Wunused-but-set-variable -DSTACK_GC_SANITY -Wall  -fno-common  -Wall -Werror -Wformat=2 -Wuninitialized -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wnested-externs -m32 -I. -Iplatform -Wdisabled-optimization -O2 -fomit-frame-pointer -falign-loops=2 -falign-jumps=2 -falign-functions=5  -c -o basis/Real/strtor.o basis/Real/strtor.c
> In file included from gc.c:47:
> gc/garbage-collection.c: In function ‘sweep’:
> gc/garbage-collection.c:708:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
>   708 |     if(!s->oneByOne)
>       |     ^~
> gc/garbage-collection.c:712:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
>   712 |  s->cGCStats.numSweeps++;
>       |  ^
> In file included from gc.c:58:
> gc/int-inf.c: In function ‘fillIntInfArg’:
> gc/int-inf.c:91:30: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>    91 |     res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                              ^
> gc/int-inf.c: In function ‘initIntInfRes’:
> gc/int-inf.c:122:28: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   122 |   res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                            ^
> In file included from gc.c:62:
> gc/new-object.c: In function ‘newThread’:
> gc/new-object.c:123:49: error: taking address of packed member of ‘struct GC_thread’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   123 |  thread->firstFrame = newStack_um(s, stackSize, &(thread->stackSizeInChunks));
>       |               

The installed version of GCC reports itself as `gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)`.  Since it's a shell script, just in case the shell version makes any difference, Bash reports its version as `GNU bash, version 5.0.11(1)-release (i686-redhat-linux-gnu)`.  I'm running the virtual machine on VirtualBox Version 6.1.8 r137981.

Was the approach described above the correct one to build RTMLton these days?  I just picked `compile.sh` since it seemed to have been updated much more recently than the other similar files apart from the Makefile itself, but I figured that the Makefile is used by the compile script.  Also, what other information would be useful to you in trying to diagnose and resolve this issue?

**Comment by jcoo092** [comment]
Ok, immediately after posting the above message, I decided to try running the compile script again, just in case it would magically work this time.  Instead, I saw further, different errors.  Ran it twice, and got different errors (I assume because the Makefile was attempting different targets).  I have copy-pasted each one for your reference, in case they are of use to you:

First run:

> gcc -std=c11  -D_GNU_SOURCE -D_USE_GNU  -Wunused-but-set-variable -DSTACK_GC_SANITY -Wall  -fno-common  -Wall -Werror -Wformat=2 -Wuninitialized -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wnested-externs -m32 -I. -Iplatform -Wdisabled-optimization -O2 -fomit-frame-pointer -falign-loops=2 -falign-jumps=2 -falign-functions=5  -c -o basis/Posix/Process/waitpid.o basis/Posix/Process/waitpid.c
> In file included from gc.c:47:
> gc/garbage-collection.c: In function ‘sweep’:
> gc/garbage-collection.c:708:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
>   708 |     if(!s->oneByOne)
>       |     ^~
> gc/garbage-collection.c:712:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
>   712 |  s->cGCStats.numSweeps++;
>       |  ^
> In file included from gc.c:58:
> gc/int-inf.c: In function ‘fillIntInfArg’:
> gc/int-inf.c:91:30: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>    91 |     res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                              ^
> gc/int-inf.c: In function ‘initIntInfRes’:
> gc/int-inf.c:122:28: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   122 |   res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                            ^
> In file included from gc.c:62:
> gc/new-object.c: In function ‘newThread’:
> gc/new-object.c:123:49: error: taking address of packed member of ‘struct GC_thread’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   123 |  thread->firstFrame = newStack_um(s, stackSize, &(thread->stackSizeInChunks));
>       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

> gcc -std=c11  -D_GNU_SOURCE -D_USE_GNU  -Wunused-but-set-variable -DSTACK_GC_SANITY -Wall  -fno-common  -Wall -Werror -Wformat=2 -Wuninitialized -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wnested-externs -m32 -I. -Iplatform -DASSERT=1 -Wno-uninitialized -O0 -g -DDEBUG=1  -c -o basis/Real/Math-gdb.o basis/Real/Math.c
> basis/Posix/Signal.c: In function ‘Posix_Signal_sigprocmask’:
> basis/Posix/Signal.c:103:50: error: passing argument 3 to restrict-qualified parameter aliases with argument 2 [-Werror=restrict]
>   103 |   return sigprocmask (how, &Posix_Signal_sigset, &Posix_Signal_sigset);
>       |                            ~~~~~~~~~~~~~~~~~~~~  ^~~~~~~~~~~~~~~~~~~~

> gcc -std=c11  -D_GNU_SOURCE -D_USE_GNU  -Wunused-but-set-variable -DSTACK_GC_SANITY -Wall  -fno-common  -Wall -Werror -Wformat=2 -Wuninitialized -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wnested-externs -m32 -I. -Iplatform -DASSERT=1 -Wno-uninitialized -O0 -g -DDEBUG=1  -c -o basis/Real/Real-consts-gdb.o basis/Real/Real-consts.c
> In file included from gc.c:47:
> gc/garbage-collection.c: In function ‘sweep’:
> gc/garbage-collection.c:708:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
>   708 |     if(!s->oneByOne)
>       |     ^~
> gc/garbage-collection.c:712:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
>   712 |  s->cGCStats.numSweeps++;
>       |  ^
> cc1: all warnings being treated as errors
> make[1]: *** [Makefile:358: basis/Posix/Signal.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> In file included from gc.c:58:
> gc/int-inf.c: In function ‘fillIntInfArg’:
> gc/int-inf.c:91:30: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>    91 |     res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                              ^
> gc/int-inf.c: In function ‘initIntInfRes’:
> gc/int-inf.c:122:28: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   122 |   res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                            ^
> In file included from gc.c:62:
> gc/new-object.c: In function ‘newThread’:
> gc/new-object.c:123:49: error: taking address of packed member of ‘struct GC_thread’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   123 |  thread->firstFrame = newStack_um(s, stackSize, &(thread->stackSizeInChunks));
>       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Second run:

> gcc -std=c11  -D_GNU_SOURCE -D_USE_GNU  -Wunused-but-set-variable -DSTACK_GC_SANITY -Wall  -fno-common  -Wall -Werror -Wformat=2 -Wuninitialized -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wnested-externs -m32 -I. -Iplatform -DASSERT=1 -Wno-uninitialized -O0 -g -DDEBUG=1  -c -o basis/System/Time-gdb.o basis/System/Time.c
> In file included from gc.c:47:
> gc/garbage-collection.c: In function ‘sweep’:
> gc/garbage-collection.c:708:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
>   708 |     if(!s->oneByOne)
>       |     ^~
> gc/garbage-collection.c:712:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
>   712 |  s->cGCStats.numSweeps++;
>       |  ^
> basis/Posix/Signal.c: In function ‘Posix_Signal_sigprocmask’:
> basis/Posix/Signal.c:103:50: error: passing argument 3 to restrict-qualified parameter aliases with argument 2 [-Werror=restrict]
>   103 |   return sigprocmask (how, &Posix_Signal_sigset, &Posix_Signal_sigset);
>       |                            ~~~~~~~~~~~~~~~~~~~~  ^~~~~~~~~~~~~~~~~~~~
> In file included from gc.c:58:
> gc/int-inf.c: In function ‘fillIntInfArg’:
> gc/int-inf.c:91:30: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>    91 |     res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                              ^
> gc/int-inf.c: In function ‘initIntInfRes’:
> gc/int-inf.c:122:28: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   122 |   res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                            ^
> In file included from gc.c:62:
> gc/new-object.c: In function ‘newThread’:
> gc/new-object.c:123:49: error: taking address of packed member of ‘struct GC_thread’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   123 |  thread->firstFrame = newStack_um(s, stackSize, &(thread->stackSizeInChunks));
>       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from gc.c:47:
> gc/garbage-collection.c: In function ‘sweep’:
> gc/garbage-collection.c:708:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
>   708 |     if(!s->oneByOne)
>       |     ^~
> gc/garbage-collection.c:712:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
>   712 |  s->cGCStats.numSweeps++;
>       |  ^

> gcc -std=c11  -D_GNU_SOURCE -D_USE_GNU  -Wunused-but-set-variable -DSTACK_GC_SANITY -Wall  -fno-common  -Wall -Werror -Wformat=2 -Wuninitialized -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wnested-externs -m32 -I. -Iplatform -DASSERT=1 -Wno-uninitialized -O0 -g -DDEBUG=1 -Wno-format-nonliteral -c -o basis/System/Date-gdb.o basis/System/Date.c
> In file included from gc.c:58:
> gc/int-inf.c: In function ‘fillIntInfArg’:
> gc/int-inf.c:91:30: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>    91 |     res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                              ^
> gc/int-inf.c: In function ‘initIntInfRes’:
> gc/int-inf.c:122:28: error: taking address of packed member of ‘struct GC_intInf’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   122 |   res->_mp_d = (mp_limb_t*)(bp->obj.limbs);
>       |                            ^
> cc1: all warnings being treated as errors

> In file included from gc.c:62:
> gc/new-object.c: In function ‘newThread’:
> gc/new-object.c:123:49: error: taking address of packed member of ‘struct GC_thread’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>   123 |  thread->firstFrame = newStack_um(s, stackSize, &(thread->stackSizeInChunks));
>       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

I hope this helps :)

**Comment by bhargavshivkumar** [comment]
Thanks for bringing this to our notice and yes, `compile.sh` is the best way to compile RTMLton.   I suspect this is a gcc version issue. Newer versions of gcc have newer warnings that we haven't handled (e.g. `-Werror=misleading-indentation `) as our gcc version is older. In any which case, I dont think you need to treat warnings as errors, its something we do during dev. Can you compile after deleting the `-Werror` [here](https://github.com/UBMLtonGroup/RTMLton/blob/conc-stacklets/runtime/Makefile#L42) and let me know if it succeeds?

**Comment by jcoo092** [comment]
Hi @bhargavshivkumar 

Yes, turning off `-Werror` does indeed get the C files building fine :)

I hit another error in the MLton compilation stage, with the following error message:

> Compiling mlton (takes a while)
> mlton @MLton ram-slop 0.7 gc-summary  -- -target self -verbose 2 -output "mlton-compile"  -link-opt -lpthread mlton-stubs.mlb
> MLton 20200628.160221-g71d17a1d6 starting
>    Compile SML starting
>       frontend starting
>          parseAndElaborate starting
> Error: ../lib/stubs/mlton-stubs/mlton.sml 64.18-64.22.
>   Variable in structure disagrees with signature (type): size.
>     structure: val size: _ -> [LargeInt.int]
>     defn at: ../lib/stubs/mlton-stubs/mlton.sml 74.11-74.14
>     signature: val size: _ -> [int]
>     spec at: ../lib/stubs/mlton-stubs/mlton.sig 28.11-28.14
> make[1]: *** [Makefile:109: mlton-compile] Segmentation fault (core dumped)
> make[1]: Leaving directory '/home/jcooper/Downloads/RTMLton/mlton'
> make: *** [Makefile:104: compiler] Error 2

The line in question in mlton.sml is `val size = MLton.size` so I would guess that it's probably an issue with my using a newer version of MLton than on your end.  Running `which mlton`, shows that mlton points to the binary that reports its version as `MLton 20200628.160221-g71d17a1d6`.

To try to get around that, I re-installed the version of MLton available from the Fedora repositories (version `MLton 20180207`) and made sure that was the one called.  That _seems_ to have worked.  Certainly, this time `make` doesn't seem to have reported errors, at least.  Thanks for your help!

Now to see if I can build [my programs](https://github.com/jcoo092/CML_benchmarks/tree/master/MLton) successfully with `mlton-compile`.

**Comment by bhargavshivkumar** [comment]
Glad it worked. RTMLton shouldn't depend on the version of MLton binaries installed. You would compile a program with RTMLton using mlton executable in  `RTMLton/build/bin/` which will be created once the compile script completes successfully.  Closing this issue.
